### PR TITLE
Add Minishift demo

### PR DESCRIPTION
**Pull request by zvikorn**
Adding description for installing Minishift and Kubevirt on top of that

### CODE REVIEW

**Comment by scollier** [comment]
LGTM

**Comment by fabiand** [comment]
Awesome!

**Comment by itamarh** [comment]
1. great to see this moving forward.
2. is minishift running in a VM? is it with nested virt or not?
3. The main readme of this github repo is focused on minikube. So one has to guess there is a minishift sample as well?
Either mention it in the beginning of the main readme, or move the minikube to readme-minikube, and have the main one point to both per user's choice?

Thanks!

**Comment by fabiand** [comment]
> great to see this moving forward.
> is minishift running in a VM? is it with nested virt or not?

Yes, minishift is using a VM as well.
No nesting, needs to be fixed in minishift

> The main readme of this github repo is focused on minikube. So one has to guess there is a minishift sample as well?

Good point, I'll add a cross reference.

> Either mention it in the beginning of the main readme, or move the minikube to readme-minikube, and have the main one point to both per user's choice?

**Pull request merged**
